swagger: '2.0'
info:
  version: 1.0.0
  title: LoopBack Application
basePath: /api
consumes:
  - application/json
  - application/x-www-form-urlencoded
  - application/xml
  - text/xml
produces:
  - application/json
  - application/xml
  - text/xml
  - application/javascript
  - text/javascript
paths:
  /artist/title:
    post:
      tags:
        - lyrics
      summary: post lyrics
      operationId: lyrics-create
      parameters:
        - name: lyrics
          in: body
          description: Model instance data
          required: false
          schema:
            $ref: '#/definitions/Lyrics'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Lyrics'
      deprecated: false
    get:
      tags:
        - lyrics
      summary: getlyrics
      operationId: lyrics-get
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
    delete:
      tags:
        - lyrics
      summary: Delete a model instance
      operationId: lyrics-delete
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
    put:
      tags:
        - lyrics
      summary: Update attributes for a model instance and persist it into the data source.
      operationId: lyrics_update
      parameters:
        - name: lyrics
          in: body
          description: Model instance data
          required: false
          schema:
            $ref: '#/definitions/Lyrics'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Lyrics'
      deprecated: false

definitions:
  Lyrics:
    properties:
      artist:
        type: string
      title:
        type: string
      lyrics:
        type: string
